### ISSUE TITLE
Implement tests for all possible responses and permissions

### ISSUE THREAD

**Issue by johnciocoiu** [creativesoftwarefdn/weaviate#169]
Implement tests for all possible responses and permissions.

Tests:
- [x] Delete forbidden: not own key or higher in tree
- [x] Search when there is nothing added to the database, or only 1 thing is added to the database, etc.
- [x] Add tests for keys, including renew - https://github.com/creativesoftwarefdn/weaviate/issues/317
- [x] Add tests for action PUT
- [x] Add tests for history statements - https://github.com/creativesoftwarefdn/weaviate/issues/302
- [x] Add tests for location URL validation - https://github.com/creativesoftwarefdn/weaviate/issues/237
- [x] Add tests for connection to another instance of Weaviate - https://github.com/creativesoftwarefdn/weaviate/issues/186
- [x] Walk through all endpoints to see possible inputs to test them all
- [x] And this one (load): https://github.com/weaviate/weaviate/issues/187
- [x] Key token header tests
- [x] Move every request to separate function?
- [x] please note the test errors here: https://travis-ci.org/creativesoftwarefdn/weaviate/builds/351550045#L1128

**Comment by bobvanluijt** [comment]
@johnciocoiu please note the test errors here: https://travis-ci.org/creativesoftwarefdn/weaviate/builds/351550045#L1128
