### ISSUE TITLE
Add public P2P architecture to Weaviate

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#396]
As described in the [architecture documentation](https://github.com/creativesoftwarefdn/weaviate/blob/develop/README.md#p2p-network).

_Note I: This does not include any actual questionare_
_Note II: This does not include a closed network as mentioned in [bullet 4](https://github.com/creativesoftwarefdn/weaviate#definitions)_
_Note III: Endpoints are already available in the Open API def_
_Note IV: [P2P feauture branch](https://github.com/creativesoftwarefdn/weaviate/tree/feature/p2p) can be used_

## Todo

- [ ] Render with Go-Swagger from new [Open-API def](https://github.com/creativesoftwarefdn/weaviate/blob/feature/p2p/openapi-specs/schema.json)
- [ ] Implement [P2P architecture](https://github.com/creativesoftwarefdn/weaviate/blob/develop/README.md#p2p-network)
- [ ] Write appropriate tests (also add to issue)

**Comment by moretea** [comment]
Merged.
