### ISSUE TITLE
Resolve Network Cross-References

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#413]
Currently, references can be made outside a Weaviate instance, this is reflected in a [single ref model](https://github.com/creativesoftwarefdn/weaviate/blob/develop/models/single_ref.go) (which in turn comes from the [open API schema doc](https://github.com/creativesoftwarefdn/weaviate/blob/develop/openapi-specs/schema.json#L550)). This should change to a P2P based approach.

Example:

```json
{
	"$cref": "[UUID]",
	"peer": "weaviate://some-other-peer's-name",
	"type": "Thing"
}
```

# Todo

- [ ] Update `SingleRef` to reflect `peer` instead of `locationUrl`.
- [ ] Allow nodes to read request data and resolve it over the P2P network.
- [ ] Allow all nodes to read from each other if accepted to the network by the genesis server.
- [ ] Reflect architecture in the readme.
- [ ] Update tests.

**Comment by bobvanluijt** [comment]
Is this still relevant @moretea or is this implement differently because of a new issue?

**Comment by moretea** [comment]
It is not implemented. This is part of a peer2peer feature.

**Comment by etiennedi** [comment]
Spiking out a happy path (WIP)

# Learnings

## Storing network ref as a vertex

### Add a vertex which we can then reference
```groovy
g.addV().property('uuid', 'some-uuid').property('kind', network_reference').property('class_id', 'Instrument').property('location', 'WeaviateB')
```

**Comment by etiennedi** [comment]
## Delivery Roadmap

### Iteration 1: Import Network Cross-Refs
Goal: without manually editing the schema first, we can import (or update) a Thing/Action with a cross-ref to a network instance.

### Iteration 2: GraphQL structure. 
Goal: We use all the info about the schema of peers to allow querying cross references on remote schemas. (Resolving is not included yet)

### Iteration 3: Resolve via network 
Goal: We can resolve one level deep over the network. (One level means a network cross-ref can not have further refs at this point)

### Iteration 4: Improve API design
We want to be able to take shortcuts in the previous iterations to move faster, however we still want to end up with the best possible UX on the API side. This iteration will "clean up" those shortcuts.

**Comment by etiennedi** [comment]
Closing as all the steps outlined in https://github.com/creativesoftwarefdn/weaviate/issues/413#issuecomment-449408411 have been completed.
