### ISSUE TITLE
Get Data from remote weaviate on { Network { Get } }

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#602]
In #515 we make sure that the GraphQL "structure" is present for `{ Network { Get } }` and point it to a network resolve. **The goal of this issue is to implement the logic for that resolver, i.e. to actually retrieve this data from a remote instance**.

## Todos 
_(not a complete list yet - it'll still grow)_
* [x] spike out possible solutions to find a simple and stable one
  * [x] can we proxy based on GraphQL "subtrees"?
  * [x] how do we want to uniquely identify other weaviates?
* [x] build resolver in `network` package
   * [x] extract subquery (without filters for now)
   * [x] proxy query to remote peer via swagger-client
   * [x] use new resolver as GraphQL Field Resolver (currently waiting for #515 to complete) 
* [x] rebuild graphql schema when peer list changes
* [x] proxy along auth headers
* [x] add support for filters
  * as of now it seems the `path` is slightly different on a `{ Local }` vs `{ Network }` query, as the first part of the path would indicate the `weaviate` name
  * [x] basic implementation
  * [x] edge (or simply other) cases, such as no operands
  * [x] validate that first element of path is an actual instance
* [x] come up with a local dev env and acceptance test path
  * it seems spinning up the entire setup twice is not a feasible development environment
  * we might introduce small fakes via the `docker-compose` setup, so that we can test two happy paths:
    * the actual weaviate is the one the user queries and is sending out a request to another (fake) weaviate
    * the actual weaviate is the one receiving a `Network { Get }` query
  * [x] start a fake genesis with `docker-compose`
  * [x] start a fake second weaviate with `docker-compose` using the graphql prototype
  * [x] get an understanding how acceptence tests currently work, finally add one for the `Network.Get`
*  ~~verify on minikube with help of helm charts~~ doesn't make sense to tackle this before #630 
*  ~~Fix documentation~~
  * ~~seems to be incorrect about Genesis Architecture (bootstrapping vs. hybrid p2p model)~~
  * ~~incorrect about how to setup a node as genesis: `environments[].P2P` does not exist anymore~~
  * ~~do we need some developer-facing docs somewhere about P2P architecture?~~
* [x] Organizational
  * [x] create follow-up issue to add support for different schemas -> #609 
  * [x] create follow-up to make network package entirely pluggable -> #621 
  * [x] create follow-up for outscoped documentation (impossible because of conflict) -> #627 
* [x] Finalizing touches: Try to refactor `graphqlapi/network`, so it gets closer to `graphqlapi/local`

##### Can we easily extract a sub-tree? 
✅ Yes, we can get that info from the specific resolver that we want to have the subtree of. For this issue this will most likely be the `Network.Get` resolver. To prove this works, here's an example from the (existing) `Local` resolver:
```go
body := p.Info.FieldASTs[0].GetLoc().Source.Body
start := p.Info.FieldASTs[0].GetLoc().Start
end := p.Info.FieldASTs[0].GetLoc().End
fmt.Printf("%s", body[start:end])
```

This prints out

```graphql
Local {
    Get {
      Things {
        City {
          name
        }
      }
    }
  }
```

#### How do we identify a weaviate?
We have agreed that all three fields (name, id, uuid) can individually be used to uniquely identify the instance.
