### ISSUE TITLE
Support different schemas in P2P network

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#609]
## Background 
As part of #515 and #602 we have made an over-simplification as an assumption: To get started quickly, we pretended that every instance on the network has the same schema/ontology. This enabled us to work on both the GraphQL parts (#515) as well as the Network Proxying Parts (#602) without having to build an elaborate schema synchronization system, first.

However, one of the selling points of Weaviate is that every instance in a P2P network can have a completely unique schema/ontology. This means that in turn every single node, needs to keep an up-to-date copy of every other instance's schema. Only then can we build the necessary GraphQL Fields and Objects for the particular network instances (which are very important from a UX perspective).

## Todos

* [x] make schema accessible in network pinging cycle
* [x] send hash along on each ping
* [x] consume hash in genesis and send on each update
* [x] in network figure out when a hash has changed on an update and download
  * [x] add simple diffing logic to find out which needs to be updated
  * [x] add dowloader to get schemas
  * [x] make downloader concurrent on many changes
  * [x] call in peerupdate cycle
* [x] in graphql build peer schemas based on actual schema cache of peers
* [x] docs (possibly include solving #627)
* [x] acceptance test 

## Proposal
* as part of the keep-alive pings we can include a hash of the current schema
* the Genesis instance can compare in each cycle whether the hash of any peer's schema has changed
* if so it sends out a broadcast like "instance 7 has a schema update"
* this in turn leads to all instances requesting the schema from instance 7 and caching it
* once a schema update was downloaded successfully a rebuild of the graphQL schema is triggered.

### Potential issues and limitations with this proposal
* If the broadcast request gets lost, a remote instance might never know that a schema has updated and keep an old (incorrect) version of a schema
  * could we instead of a broadcast message rely on a pull-based system instead. This way we could constantly compare desired state with actual state. If a network request gets dropped, we would simply compare the next iteration again.
* There is a short period between when the schemas across the network will not be consistent:
  * `weaviateA` updates their schema at 16:03:00
  * `weaviateA` sends the next regular keep-alive ping to the genesis at 16:03:30
  * The genesis realizes an update is necessary and sends a broadcast message at 16:03:45
  * `weaviateB` receives the broadcast and immediately downloads the new schema, finished at 16:03:55
  * If a user of `weaviateB` tries to do a `Network.Get` to `weaviateA` any time between 16:03:00 and 16:03:55 they will have an incorrect schema and the request could fail
  * I think this temporary inconsistency of schemas is OK in a P2P network, but we have to be aware of it.

Thoughts, comments, ideas on all of the above?
@moretea @bobvanluijt @idcrosby @JeroenStravers1

**Comment by bobvanluijt** [comment]
Hi @etiennedi, 

The proposal seems fine in general.

I would like to introduce an _additional_ idea for syncing. The Weaviates use the P2P endpoint to sync. What you _could_ do is this:
- When `Weaviate-A` requests something from `Weaviate-B` using the P2P endpoint, we could add the hash of the current schema in the body. If `Weaviate-B` receives the wrong hash, it can push the update again. Note that this would be _additional_ and not a replacement.
- You can keep pinging hashes around over the network.

**Comment by etiennedi** [comment]
In this case it would be the expected hash right? `A` queries `B` and expects `B` to have hash `afd0f23`. If `B` has a different hash, it'll trigger on update.

So I'd like the expectation to be contained in the naming.

Additionally, we might want to distinguish between a schema hash and a contextionary hash (and possibly other configurable things), so we might end up at `X-Weaviate-Expected-Schema-Hash` (not sure if we really need the 'Weaviate' in there?)

**Comment by etiennedi** [comment]
On second though, `Expected` is not a good word. `Expected` implies that this is the one and only truough. But the expectation is only wrong because `A` had outdated data.

So, maybe we should call it `cached`, like `X-Weaviate-Cached-Schema-Hash`.

**Comment by bobvanluijt** [comment]
The upside of using a cache of hashes also might solve another problem: who's wrong?

Example: `Weaviate A` queries `Weaviate B`. `Weaviate A` sends a hash that `Weaviate B` doesn't recognize.

If `Weaviate B` has the hash cached, it knows `Weaviate A` is outdated.

What is important, is that we extend the flow [mentioned here](https://github.com/creativesoftwarefdn/weaviate#p2p-network).

**Comment by etiennedi** [comment]
> What is important, is that we extend the flow mentioned here.

From what I can tell most of this doc is quite outdated, right? Especially the diagrams. They still assumes the non-hybrid P2P approach, i.e. the genesis weaviate turning into  a regular weaviate after a second node has joined. But what I got from @moretea you have agreed to do a hybrid model, where one instance will always stay the genesis. It also mentions endpoints that don't exist anymore like `/p2p/echo` or `/p2p/announce`, etc.

I can clean up this doc as part of #602, I have to add new some new explanations of how the architecture for the `Network.Get` works to it anyway.

**Comment by bobvanluijt** [comment]
Aha, I assumed the docs were in line with the changes. Please wait with updating them though. I'm pushing a big change to the docs in the coming week.

**Comment by etiennedi** [comment]
Ok, good to know. Then I won't introduce the documentation on the feature branch for #602 yet, but rather wait for your update.

On the state of the docs, from what I can tell, they were updated in parts, but not all the way through. The first paragraph definitely mentions the hybrid approach, but then further down with the 4 diagrams, both the lists and the diagrams describe rather a non-hybrid, but pure p2p appraoch.

@moretea - Please correct me if I'm wrong here.

**Comment by etiennedi** [comment]
@bobvanluijt I have started building this feature (i.e. "make weaviate aware of the schemas of all it's peers") as it's in my opinion the logical conclusion of having completed #602. 

However, to not over-engineer it I might first built a version that doesn't have the advanced cache-invalidation via hashes sent on every request. But at first, rather rely on the regular genesis pings to broadcast hash changes. If this goes faster than expected - or doesn't seem stable enough - I'd continue with the advanced hashing cache invalidation we discussed in the previous comments.

All of that of course assumes there is nothing more urgent that needs my attention right now, if you can think of something please let me know.
