### ISSUE TITLE
Clean up TODO's

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#611]
By running this script, i looked at all code that I added that contains the magic word 'TODO'.

<details>

```python3
#!/usr/bin/env nix-shell
#! nix-shell -p python36 -i python3

import os
import subprocess

for root, dirs, files in os.walk("."):
    for file in files:
        if file == '.git':
            continue
        full_path = root + "/"+ file

        result = subprocess.run("git blame {} | grep -i todo | grep Maarten".format(full_path), shell=True, stdout=subprocess.PIPE)
        if result.returncode == 0:
            print("<details>")
            print("<summary>")
            print(full_path)
            print("</summary>")
            print("<code><pre>")
            print(result.stdout.decode("utf-8").strip())
            print("</pre></code>")
            print("</details>")
```

</details>

### Found TODO's

<details>
<summary>

- [x] ./genesis/client/operations/operations_client.go

</summary>
<code><pre>
91f022281 (Maarten Hoogendoorn 2018-07-19 12:50:00 +0200  31) 	// TODO: Validate the params before sending
91f022281 (Maarten Hoogendoorn 2018-07-19 12:50:00 +0200  59) 	// TODO: Validate the params before sending
91f022281 (Maarten Hoogendoorn 2018-07-19 12:50:00 +0200  87) 	// TODO: Validate the params before sending
91f022281 (Maarten Hoogendoorn 2018-07-19 12:50:00 +0200 115) 	// TODO: Validate the params before sending
</pre></code>
</details>

<details>
<summary>

- [x] ./genesis/restapi/server.go

</summary>
<code><pre>
7f2ad4f25 (Maarten Hoogendoorn 2018-07-18 15:34:39 +0200 399) 	ctx, cancel := context.WithTimeout(context.TODO(), 15*time.Second)
</pre></code>
</details>

<details>
<summary>

- [x] ./genesis/restapi/configure_weaviate_genesis.go

</summary>
<code><pre>
e8e59c925 (Maarten Hoogendoorn 2018-07-19 12:46:51 +0200  67) 		//TODO: perform ping action on weaviate
</pre></code>
</details>

<details>
<summary>

- [x] ./graphqlapi/local/get_meta/get_meta.go

</summary>
<code><pre>
df842575c (Maarten Hoogendoorn 2018-12-05 12:55:24 +0100  79) 			// TODO: not implemented yet.
</pre></code>
</details>

<details>
<summary>

- [x] ./graphqlapi/local/get/resolver.go

</summary>
<code><pre>
7e2c2ddb2 (Maarten Hoogendoorn 2018-11-24 16:49:44 +0100 34) // TODO move from ClassName and Properties to SelectClass in LocalGetClassParams.
</pre></code>
</details>

<details>
<summary>

- [x] ./graphqlapi/local/get/get.go

</summary>
<code><pre>
df842575c (Maarten Hoogendoorn 2018-12-05 12:55:24 +0100 139) 					// TODO
5f255db6a (Maarten Hoogendoorn 2018-11-09 10:15:23 +0100 228) 							// TODO: inspect type of result.
5f255db6a (Maarten Hoogendoorn 2018-11-09 10:15:23 +0100 236) 					// TODO: Check cardinality
</pre></code>
</details>

<details>
<summary>

- [x] ./client/meta/meta_client.go

</summary>
<code><pre>
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200 33) 	// TODO: Validate the params before sending
</pre></code>
</details>

<details>
<summary>

- [x] ./client/keys/keys_client.go

</summary>
<code><pre>
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200  33) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200  64) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200  95) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200 126) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200 157) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200 188) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200 219) 	// TODO: Validate the params before sending
</pre></code>
</details>

<details>
<summary>

- [x] ./client/actions/actions_client.go

</summary>
<code><pre>
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200  33) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200  64) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200  95) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200 132) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200 163) 	// TODO: Validate the params before sending
0bac100ce (Maarten Hoogendoorn 2018-11-06 23:23:34 +0100 194) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200 225) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200 355) 	// TODO: Validate the params before sending
</pre></code>
</details>

<details>
<summary>

- [x] ./client/p2_p/p2_p_client.go

</summary>
<code><pre>
0dbed8c19 (Maarten Hoogendoorn 2018-07-20 09:22:19 +0200 31) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200 61) 	// TODO: Validate the params before sending
</pre></code>
</details>

<details>
<summary>

- [x] ./client/graphql/graphql_client.go

</summary>
<code><pre>
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200 33) 	// TODO: Validate the params before sending
</pre></code>
</details>

<details>
<summary>

- [x] ./client/schema/schema_client.go

</summary>
<code><pre>
cfe7352a8 (Maarten Hoogendoorn 2018-10-23 16:20:38 +0200  31) 	// TODO: Validate the params before sending
cfe7352a8 (Maarten Hoogendoorn 2018-10-23 16:20:38 +0200  60) 	// TODO: Validate the params before sending
cfe7352a8 (Maarten Hoogendoorn 2018-10-23 16:20:38 +0200  89) 	// TODO: Validate the params before sending
cfe7352a8 (Maarten Hoogendoorn 2018-10-23 16:20:38 +0200 118) 	// TODO: Validate the params before sending
cfe7352a8 (Maarten Hoogendoorn 2018-10-23 16:20:38 +0200 147) 	// TODO: Validate the params before sending
cfe7352a8 (Maarten Hoogendoorn 2018-10-23 16:20:38 +0200 176) 	// TODO: Validate the params before sending
fe847ecdd (Maarten Hoogendoorn 2018-09-12 13:50:34 +0200 205) 	// TODO: Validate the params before sending
fe847ecdd (Maarten Hoogendoorn 2018-09-12 13:50:34 +0200 234) 	// TODO: Validate the params before sending
fe847ecdd (Maarten Hoogendoorn 2018-09-12 13:50:34 +0200 263) 	// TODO: Validate the params before sending
fe847ecdd (Maarten Hoogendoorn 2018-09-12 13:50:34 +0200 292) 	// TODO: Validate the params before sending
fe847ecdd (Maarten Hoogendoorn 2018-09-12 13:50:34 +0200 321) 	// TODO: Validate the params before sending
fe847ecdd (Maarten Hoogendoorn 2018-09-12 13:50:34 +0200 350) 	// TODO: Validate the params before sending
fe847ecdd (Maarten Hoogendoorn 2018-09-12 13:50:34 +0200 379) 	// TODO: Validate the params before sending
</pre></code>
</details>

<details>
<summary>

- [x] ./client/things/things_client.go

</summary>
<code><pre>
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200  33) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200  64) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200 101) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200 132) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200 163) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200 194) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200 324) 	// TODO: Validate the params before sending
1a3e48336 (Maarten Hoogendoorn 2018-07-19 13:15:13 +0200 355) 	// TODO: Validate the params before sending
</pre></code>
</details>

<details>
<summary>

- [x] ./database/database.go

</summary>
<code><pre>
bd0faf467 (Maarten Hoogendoorn 2018-11-04 23:59:43 +0100 44) 	// TODO: probably needs to go. We're not using address anymore.
</pre></code>
</details>

<details>
<summary>

- [x] ./database/schema_manager/local/local.go

</summary>
<code><pre>
cd282adf9 (Maarten Hoogendoorn 2018-10-08 16:40:04 +0200  45) // TODO: refactor to database/schema_manager, so that it can be re-used for distributed version.
b932a6013 (Maarten Hoogendoorn 2018-10-03 15:42:39 +0200 222) 	// TODO not 100% robust against failures.
</pre></code>
</details>

<details>
<summary>

- [x] ./database/schema_manager/local/manager.go

</summary>
<code><pre>
cd282adf9 (Maarten Hoogendoorn 2018-10-08 16:40:04 +0200  38) 		// TODO keep it sorted.
3f4a3b4a4 (Maarten Hoogendoorn 2018-10-08 17:42:53 +0200  51) 	// TODO keep it sorted.
0e80689ca (Maarten Hoogendoorn 2018-10-24 12:10:20 +0200  75) 	// TODO log
</pre></code>
</details>

<details>
<summary>

- [x] ./database/connectors/janusgraph/things.go

</summary>
<code><pre>
b6f7cd0bf database/connectors/janusgraph/things.go (Maarten Hoogendoorn 2018-11-04 23:59:43 +0100 45) 	// TODO: Optimize query to perform just _one_ JanusGraph lookup.
</pre></code>
</details>

<details>
<summary>

- [x] ./database/connectors/janusgraph/migrator.go

</summary>
<code><pre>
4796049dd database/connectors/janusgraph/migrator.go (Maarten Hoogendoorn 2018-11-04 23:59:43 +0100  56) 		// TODO: await answer from janus consultants; it's not avaible in our janus setup.
96493c6c2 database/connectors/janusgraph/migrator.go (Maarten Hoogendoorn 2018-11-04 23:59:43 +0100 243) //// TODO: add to Gremlin DSL
</pre></code>
</details>

<details>
<summary>

- [x] ./database/connectors/janusgraph/keys.go

</summary>
<code><pre>
9af85e3a8 connectors/janusgraph/keys.go          (Maarten Hoogendoorn 2018-08-21 14:11:35 +0200  29) //TODO fix keys cross weaviates.
</pre></code>
</details>

<details>
<summary>

- [x] ./database/connectors/janusgraph/helper.go

</summary>
<code><pre>
7e8be060a (Maarten Hoogendoorn 2018-11-06 23:03:37 +0100 540) 	// TODO verify that indeed this is the desired behaviour.
fab30d807 (Maarten Hoogendoorn 2018-11-06 17:06:44 +0100 601) 		// TODO; reformat?
</pre></code>
</details>

<details>
<summary>

- [x] ./database/connectors/janusgraph/actions.go

</summary>
<code><pre>
cac3cb0c1 database/connectors/janusgraph/actions.go (Maarten Hoogendoorn 2018-11-06 23:39:35 +0100 45) 	// TODO: Optimize query to perform just _one_ JanusGraph lookup.
</pre></code>
</details>

<details>
<summary>

- [x] ./contextionary/annoyindex/annoylib.h

</summary>
<code><pre>
a266df86c (Maarten Hoogendoorn 2018-07-11 08:34:31 +0200  89)         // TODO: this is turned on by default, but may not work for all architectures! Need to investigate.
a266df86c (Maarten Hoogendoorn 2018-07-11 08:34:31 +0200 292)     Node<S, T>* p = (Node<S, T>*)malloc(s); // TODO: avoid
a266df86c (Maarten Hoogendoorn 2018-07-11 08:34:31 +0200 293)     Node<S, T>* q = (Node<S, T>*)malloc(s); // TODO: avoid
a266df86c (Maarten Hoogendoorn 2018-07-11 08:34:31 +0200 457)     Node<S, T>* p = (Node<S, T>*)malloc(s); // TODO: avoid
a266df86c (Maarten Hoogendoorn 2018-07-11 08:34:31 +0200 458)     Node<S, T>* q = (Node<S, T>*)malloc(s); // TODO: avoid
a266df86c (Maarten Hoogendoorn 2018-07-11 08:34:31 +0200 490)     Node<S, T>* p = (Node<S, T>*)malloc(s); // TODO: avoid
a266df86c (Maarten Hoogendoorn 2018-07-11 08:34:31 +0200 491)     Node<S, T>* q = (Node<S, T>*)malloc(s); // TODO: avoid
a266df86c (Maarten Hoogendoorn 2018-07-11 08:34:31 +0200 599)       // TODO: throw exception
a266df86c (Maarten Hoogendoorn 2018-07-11 08:34:31 +0200 789)     Node* m = (Node*)malloc(_s); // TODO: avoid
a266df86c (Maarten Hoogendoorn 2018-07-11 08:34:31 +0200 836)     Node* v_node = (Node *)malloc(_s); // TODO: avoid
</pre></code>
</details>

<details>
<summary>

- [x] ./gremlin/response.go

</summary>
<code><pre>
9af85e3a8 (Maarten Hoogendoorn 2018-08-21 14:11:35 +0200 60) 	// TODO
</pre></code>
</details>

<details>
<summary>

- [x] ./gremlin/response_property.go

</summary>
<code><pre>
9af85e3a8 (Maarten Hoogendoorn 2018-08-21 14:11:35 +0200  96) 			//TODO fix; read up on where/how this is possible.
</pre></code>
</details>

<details>
<summary>

- [x] ./gremlin/dsl_helper.go

</summary>
<code><pre>
9af85e3a8 (Maarten Hoogendoorn 2018-08-21 14:11:35 +0200  9) // TODO figure out other ways of doing string interpolation in Groovy and escape them.
</pre></code>
</details>

<details>
<summary>

- [x] ./gremlin/http_client/execute.go

</summary>
<code><pre>
9af85e3a8 (Maarten Hoogendoorn 2018-08-21 14:11:35 +0200 80) 		// TODO return status message
</pre></code>
</details>

<details>
<summary>

- [x] ./test/acceptance/keys/keys_test.go

</summary>
<code><pre>
aeb572246 test/acceptance/keys_test.go      (Maarten Hoogendoorn 2018-08-21 20:34:38 +0200 102) 			// TODO in old tests known as newSubAPIToken
aeb572246 test/acceptance/keys_test.go      (Maarten Hoogendoorn 2018-08-21 20:34:38 +0200 133) // TODO Convert this to a Unit test.
</pre></code>
</details>

<details>
<summary>

- [x] ./test/acceptance/things/things_test.go

</summary>
<code><pre>
aeb572246 test/acceptance/things_test.go        (Maarten Hoogendoorn 2018-08-21 20:34:38 +0200 183) 		/* TODO: don't count nr of elements in validation. Just validate keys, and _also_ generate an error on superfluous keys.
</pre></code>
</details>

<details>
<summary>

- [x] ./restapi/configure_weaviate.go

</summary>
<code><pre>
6765d8178 restapi/configure_weaviate.go  (Maarten Hoogendoorn 2018-09-13 14:49:28 +0200  587) 			//TODO: handle errors
6765d8178 restapi/configure_weaviate.go  (Maarten Hoogendoorn 2018-09-13 14:49:28 +0200 1483) 	// TODO  make this configureable
bd0faf467 restapi/configure_weaviate.go  (Maarten Hoogendoorn 2018-11-04 23:59:43 +0100 1492) 	// TODO: make part of schema manager?
bd0faf467 restapi/configure_weaviate.go  (Maarten Hoogendoorn 2018-11-04 23:59:43 +0100 1513) 			// TODO: turn on safe mode
0e80689ca restapi/configure_weaviate.go  (Maarten Hoogendoorn 2018-10-24 12:10:20 +0200 1592) 	//TODO: update on schema change.
</pre></code>
</details>

<details>
<summary>

- [x] ./restapi/handlers_schema.go

</summary>
<code><pre>
b75adf31d (Maarten Hoogendoorn 2018-10-23 17:02:37 +0200 113) 		// TODO: This implies that we can't undo setting keywords, because we can't detect if keywords is not present, or empty.
b75adf31d (Maarten Hoogendoorn 2018-10-23 17:02:37 +0200 144) 		// TODO: This implies that we can't undo setting keywords, because we can't detect if keywords is not present, or empty.
b75adf31d (Maarten Hoogendoorn 2018-10-23 17:02:37 +0200 263) 		// TODO: This implies that we can't undo setting keywords, because we can't detect if keywords is not present, or empty.
b75adf31d (Maarten Hoogendoorn 2018-10-23 17:02:37 +0200 294) 		// TODO: This implies that we can't undo setting keywords, because we can't detect if keywords is not present, or empty.
</pre></code>
</details>

<details>
<summary>

- [x] ./restapi/server.go

</summary>
<code><pre>
5f7115efd restapi/server.go  (Maarten Hoogendoorn 2018-07-16 11:04:28 +0200 432) 	ctx, cancel := context.WithTimeout(context.TODO(), 15*time.Second)
</pre></code>
</details>

<details>
<summary>

- [x] ./network/p2p_network.go

</summary>
<code><pre>
e6f3b4a09 (Maarten Hoogendoorn 2018-07-19 16:57:21 +0200  89) 	time.Sleep(10) //TODO: Use channel close to listen for when complete configuration is done.
</pre></code>
</details>

<details>
<summary>

- [x] ./network/network.go

</summary>
<code><pre>
e6f3b4a09 (Maarten Hoogendoorn 2018-07-19 16:57:21 +0200 24) 	// TODO: We'll add functions like
</pre></code>
</details>
