### ISSUE TITLE
Optimize Janus queries from N+1 to 1 queries.

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#612]

**Comment by etiennedi** [comment]
## Todos

* [x] for GraphQL `Local Get`
* [ ] for REST API
* [ ] refactor duplication in `helpers.go` in `janus` package

**Comment by etiennedi** [comment]
Was merged, but issue never closed. Closing now.
