### ISSUE TITLE
Update p2p documentation

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#627]
It's a bit outdated, still talks about a pure P2P approach as opposed to the Hybrid P2P approach.

Originally we wanted to update the docs as part of #602, but with #622 ongoing in parallel, this would only lead to merge conflicts en masse.

So instead, we're scoping this out from #602 and tackling it in here at some point after #622 is finished.

## Todos
* [ ] seems to be incorrect about Genesis Architecture (bootstrapping vs. hybrid p2p model)
* [ ] incorrect about how to setup a node as genesis: `environments[].P2P` does not exist anymore
* [ ] do we need some developer-facing docs somewhere about P2P architecture?
