### ISSUE TITLE
Resolve Local.Fetch.{Things,Actions}

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#645]
## Todos
* [x] make sure contextionary is re-built after a schema change (#618)
* [x] add querying layer on top of contextionary that allows searching by either class or class+keywords
  * the current setup exposes to many internals (vectors, kNN) that should not spill out of the contextionary package
  * this will make actual querying much easier
  * we are currently exposing the `$[THING]className` format. This should be an implemenation detail and not exposed
  * [x] search for classes
  * [x] support additional keywords for classes
  * [x] search for properties
  * [x] support additional keywords for properties
  * [x] include/exclude items based on certainty
  * [x] validate search params
  * [x] take into account special meaning of CamelCasing
    * [x] compute centroid of camelCased class Name
    * [x] fail validation for camelCased keywords (they should be multiple instead)
* [x] build local way to query
  * [x] build `Local { Fetch }` in GraphQL
      * [x] port over from `Network { Fetch }`
      * [x] refactor descriptions -> unnecessary suffix Desc
      * [x] remove global variables from graphql package local package
  * [x] extract info from GraphQL query
    * [x] extract class info
    * [x] extract property info
    * [x] extract more than one property
    * [x] extract property search params
  * [x] find desired classes in database
    * [x] write query builder that takes into account the results from the c11y
      * [x] for simple prop/class combinations
      * [x] for advanced combinations (i.e. multiple props, each with multiple alternative class and property names)
      * [x] validate schema types to prevent us from database-typing errors
      * [x] for all operator types / propType combinations
        * [x] int
        * [x] string
        * [x] date
        * [x] text
        * [x] number
        * [x] bool
    * [x] connect query builder in connector(s)
    * [x] deal with special case for emtpy results
      * [x] don't propagate to connector if we didn't find classes/properties
      * [x] make sure we still have a viable query even if we can't find a single pair of class/props to filter for
    * [x] write post-processor to form beacon structure and the ability to calculate certainty
  * ~~This is currently depending the decision of whether we want to add a `Local { Fetch }` GraphQL API as well. If so, it will contain the parts to complete this. If not, it will be a REST endpoint.~~
    * :white_check_mark: We have decided to add a `Local { Fetch }` as well
* ~~build network proxying and aggregation part~~
  * ~~remove global variables from network package~~
  * outscoped to #709
* [x] change graphQL schema to make sure only a single class can be specified (cc @laura-ham)
  * [x] in prototype
  * [x] in weaviate
* [x] add acceptance test

## Research
* [x] How are keywords currently handled? Are they used at all
  * The current assumption is that a centroid of className and keywords will produce much better kNN-Results than just the className
  * Yes, keywords are on import added to the schema config (currently saved in etcd)
  * Since we don't have the querying layer (outlined in TODOs), we also don't have anything that makes use of them yet.
* [x] How do we translate the specified certainty (relative value between 0..1) into an absolute value (kNN distance) which we get from the c11y? (cc @laura-ham)
  * there will most likely be a logarithmic model in the future
  * we don't have the exact model yet
  * we want to build it as flexible as possible, so we might start with a simple linear model, that we can very easily replace
* [x] find query that allows multiple classnames and allows matching for multiple properties

**Comment by etiennedi** [comment]
@laura-ham @bobvanluijt Network Fetch is among the features I could tackle next and I have some questions.

Using the example from the Docs:
```graphql
{
  Network {
    Fetch {
      Things(where: {
        class: [{
          name: "Animal",
          keywords: [{
            value: "Mammal",
            weight: 0.9
          }],
          certainty: 0.8
        }],
        properties: [{
          name: "name",
          keywords: [{
            value: "identifier",
            weight: 0.9
          }],
          certainty: 0.8,
          operator: Equal,
          valueString: "Bella"
        }]
      }) {
        beacon
        certainty
      }
    }
  }
}
```

1. How much of the matching is due to the user specifying attributes vs calculating based on Contextionary values. For example, the query above states `A class called "Animal" or with the keyword "Mammal" with a weight of 0.9`. Do I understand it correctly that we don't need the contextionary yet at this point because this is all info that's in the schema? (The same question of course also applies for `properties` rather than classes)
2. What does the certainty on the `class` mean? I guess the answer to this depends on Question 1 as well. One possible interpretation I could come up with is: We apply the criteria from question 1, this gives us e.g. 2 classes. Now in a second step we use the contextionary and ask "which other classes using a certainty of 0.8" are similar to my original two?" In this case we might end up with e.g. 5 classes.
3. What does the certainty on the `property` mean? (Probably very much dependent on the answer to question 1+2) Does it mean "all properties that match `name: "name"` with a certainty of 0.8 should be used". Or does it mean `valueString: "Bella"` has to match with a certainty of 0.8?
4. How is the overall certainty in the result calculated?
5. Is this as easy to use as it should be? I have plenty of questions on this even with the context I have on weaviate and the contextionary. A potential user without this context could be even more confused. Maybe it would help if the example in the docs is more gradual, i.e. first have one that does not include keywords at all (assuming they aren't required?), then have a full-fledged example. Maybe in each example add a comment after each line explaining what it does?

**Comment by etiennedi** [comment]
> Hope this helps!
Yes, thanks definitely, some follow ups:

1. What you write makes sense, but I don't understand yet what the point of the `keywords` is then. Could you give me an example for a result both with keywords and without keywords specified and highlight the differences? Or maybe outline in what order which specified fields (`certainty` vs `keywords`) are evaluated?
2. got it, thanks 
3. got it, thanks
4. Ok, cool, I think it might make sense to go for a first implementation without calculating the `certainty` in the response and then iterate from there
5. makes sense

**Comment by laura-ham** [comment]
> Could you give me an example for a result both with keywords and without keywords specified and highlight the differences? Or maybe outline in what order which specified fields (certainty vs keywords) are evaluated?

I think the keywords are extra information for the user to put in the query. If you want results about airplanes, and you can put in `Plane` as classname. But because you know (as a user) that the word `plane` is ambiguous (with meanings like Airplane or Level/surface), you can add keywords you know that are associated with the kind of `plane` you mean. So in the case of airplane this could be `Airplane`, `Airport`, `Transport` etc. While if you are looking for the other meaning you could add `Surface`, `Level` etc as keywords.

> Ok, cool, I think it might make sense to go for a first implementation without calculating the certainty in the response and then iterate from there.

Sure, I think it's good to start small and explore what functions are required/preferred and can be implemented next.

**Comment by etiennedi** [comment]
Thanks, the explanation helps. I didn't think of disambiguation before. However, I'm still not quite sure at what point the keywords should be applied while resolving a `Fetch` query.

Using your example above what would happen in either Scenario?

### Scenario 1: no keywords
User says `Plane` with certainty `0.8`. 

Q1: Which classes do we return? 
Q2: How did we determine whether to include or exclude a potential class?

### Scenario 2: with keyword `Airplane`
The user knows that `Plane` is ambiguous, so he makes sure to provide the keyword `Airplane` with a high weight.

Q1: Which classes do we return? 
Q2: How did we determine whether to include or exclude a potential class?

To take this one step further. Is there a difference between the following two:
2a) During schema creation the keyword `Airplane` was added to the class `Plane`
2b) During schema creation the keyword `Airplane` was NOT added to the class `Plane`?

If yes, how does this influence both Q1 and Q2?

Sorry for all the questions, but properly understanding the intentions is probably a good prerequisite before starting to build the feature :)

**Comment by bobvanluijt** [comment]
Thanks, let me know if you get stuck here @etiennedi and @laura-ham.

**Comment by etiennedi** [comment]
[This finding](https://github.com/creativesoftwarefdn/weaviate/issues/618#issuecomment-460626928) might be another argument pro "every peer uses their own contextionary", as it would reduce the overall complexity: https://github.com/creativesoftwarefdn/weaviate/issues/618#issuecomment-460626928. However, it's not a very strong argument, so if we find a strong argument against this distributed approach it might still tip the scales.

**Comment by bobvanluijt** [comment]
Oef, this is a difficult thing. Currently, I communicate that Weaviate networks _should_ have a similar contextionary.

**Comment by etiennedi** [comment]
@bobvanluijt I meant, each peer should use the local contextionary to run the queries/searches against (rather than the querying peer running the searches for all peers). This still assumes all contextionaries are more or less in sync.
