### ISSUE TITLE
Resolve Network.Fetch.Fuzzy

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#647]
`Fetch { Fuzzy }` is a comfortable way to search for strings by traditional metrics (such as levensthein distance) and contextionary-aided searches. 

# Todos

* [x] extend contextionary with safe search option
* ~~(optional) extend already extracted contextionary in similar fashion~~
* [x] build fuzzy search in gql package (note: this two layered arch isn't optimal, it'd be much better in three layers, but this is not something we can change now)
* [x] build db connector search
* [x] acceptance test for local
* [x] build proxy for network
  * [x] implement gql logic
  * [x] implement proxying in network package
  * [x] make sure localhost is replaced with peer name
  * [x] acceptance test for network
* [x] update connector docs
* [x] include className for all fetch queries

**Comment by etiennedi** [comment]
@laura-ham The className is now added to all Fetch queries. (Also not the type in "Berlin", yet it matches because of the levensthein-based fuzzy matching in Janusgraph 😉)

Feel free to push the doc changes to branch `feature/fetch_fuzzy`. I'll wait before creating a PR until all the changes are in.

![image](https://user-images.githubusercontent.com/8974479/55546479-b6680480-56cf-11e9-92a6-d6b4ba67668e.png)
