### ISSUE TITLE
Resolve Network Cross-References over Network

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#660]
As outlined in #413 we want to resolve network cross-refs.

Depends on #659 

## Todos
* [x] investigate open `TODO`s for cardinality and ResolveType in Class Union
  * there was an issue in `go-graphql` v0.7.5 -> whenever a resolver returned a thunk, it wouldn't bubble up to the higher resolvers (graphql-go/graphql#340)
* [x] clean up technical debt resulting from go-graphql bug mentioned above
  * [x] first remove thunk to enable bubbling up through the resolvers
  * [x] add the required resolvers and type resolvers
  * [x] re-introduce thunks to add parallelism again
  * [x] clean ups for GetMeta
* [x] resolve cross-ref
  * [x] proxy to separate instance from refField resolver
  * [x] make sure we don't send a request if the user doesn't want the network ref
  *  ~~include auth headers~~ no point in building something specific to the key-based auth now, if we want to remove that in #646 
  * [x] enable concurrency through thunks
* [x] add acceptance test
