### ISSUE TITLE
Apply where filters in Janus, not in Go binary after retrieval

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#680]
## Goal
Use Gremlin capabilities of Janusgraph to apply the `where` filters we get from the user via GraphQL.

## Background
The current implementation seems to always query all results from weaviate and then apply the filters later in Go, see https://github.com/creativesoftwarefdn/weaviate/blob/77c47eba099651c2d122a3902292ef49b945924f/database/connectors/janusgraph/resolver_get.go#L88-L90

~~My assumption is~~ *It has been confirmed* that this was a minimal implementation to move faster. However, this creates a few issues, namely that we apply the filters on paginated results. Additionally it makes it rather impossible to filter through huge data sets, which is an important requirement for weaviate.

## Todos
*new todos will be added as the plan becomes more clear*
* [x] get an understanding of filters currently work
  * generally a flat list, one item per filter, however the `On` prop can be nested infinitely
* [x] spike out a success case for a primitive prop
  * success! see commit msg for details: 8c5f661
* [x] filters for cross-refs
  * [x] one level deep
  * [x] n levels deep
* [x] single Filters for Primitive Props
  * [x] int
  * [x] number
  * [x] string
  * [x] boolean
  * [x] date
* [x] combine filters with `and` and `or`
* [x] add ability to replace class and prop names with mapped names
