### ISSUE TITLE
Support horizontal scaling of weaviate

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#685]
## Goal
To support very large workloads we want to make sure weaviate can be scaled horizontally 

## What's preventing us?
Weaviate is mostly a stateless application, however, at the moment two things are keeping us from achieving horizontal scalability:

1. Weaviate writes into the local file system. These files describe the schema state of the database. If a database has already been initialized, but weaviate is missing this information it will not be able to start up
2. To change the schema we need to lock database access (including reads). This (distributed) lock must be shared by all replicas of weaviate

**Comment by etiennedi** [comment]
# POC with `etcd`

## Questions to be answered
* Can we use `etcd` to replace the file-system writing?
* Can we use `etcd` to replace the locking mechanism?
* How big of a challenge is it?
* What new problems arise that we have to tackle?

## Todos
* [ ] include `etcd` in `docker-compose`
* [ ] try out locking mechanism as independent spike
* [ ] try saving/reading one of the files in etcd instead.
  * [ ] Deal with potential fallout
* [ ] understand where current locks are applied and how/what they lock
* [ ] try replacing a lock with `etcd`
* [ ] can we test with concurrent weaviates locally?

**Comment by etiennedi** [comment]
@bobvanluijt The PR (#702) is now ready :)

**Comment by bobvanluijt** [comment]
wonderful
