### ISSUE TITLE
Resolve Local.Aggregate

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#693]
## Description
Resolve the GraphQL Responses for Local.Aggregate based on grouping parameters

[Related Documentation](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/use/graphql_grouping.md)

## Todos
* [x] switch structure in GraphQL API (from `aggregatorFn->property` to `property->aggregatorFn`)
  * [x] local
  * [x] network
* [x] extract desired selections from graphQL in resolver
  * [x] extract aggregators
  * [x] extract grouping path (should it be parsed as well?)
  * [x] common filters
* [x] add query builder and post processor for
  * [x] grouping by primitive prop
  * [x] grouping by ref prop
  * [x] grouping by nested ref prop
  * [x] aggregate methods for numerical props
    * [x] `maximum`
    * [x] `minimum`
    * [x] `mean`
    * [x] `mode` (might depend on external help, might be scoped out)
    *  ~~`median` (might depend on external help, might be scoped out)~~ will be scoped out into seperate task
    * [x] `count` 
  * [x] aggregate method (it's only `count`) for non-numerical props
    * [x] non-ref props
    * [x] ref-props
  * [x] handle special case when only a single aggregator is required (make sure to use `project()` in `select().by()`
  * [x] handle special case when only a single property is required (make sure to use `project()` in `select().by()`
  * [x] postprocess property names to remove prefix and transform map into slice, as expected by the graphQL api
  * [x] display `groupedBy { value path }` in query result
* [x] combine local aggregate with `where` filters
* [x] refactor: unify graphql `local/getmeta`, `network/getmeta` and `network/aggregate`, they share a lot of code but right now all are slightly different and there's plenty of unnecessary duplication
* [x] create required follow-up issues

## Research tasks
* [x] Gremlin query to group by primitive props
* [x] Gremlin query to group by ref prop one level deep
```groovy
g.V().has("kind", "thing").has("classId", "class_3").group().by(
  out("prop_17").values("prop_1e")
).by(
  fold()
    .match(
      __.as("a").count(local).as("count"),
      __.as("a").unfold().values("prop_18").mean().as("population__mean"),
      __.as("a").unfold().values("prop_18").max().as("population__max")
    )
      .select("count", "population__mean", "population__max")
  )
```
results in:
```json
{
  "data": [
    {
      "Germany": {
        "count": 2,
        "population__max": 3470000,
        "population__mean": 2035000
      },
      "Netherlands": {
        "count": 2,
        "population__max": 1800000,
        "population__mean": 1800000
      }
    }
  ],
  "meta": {}
}
```
* [x] Gremlin query to group by ref prop n levels deep
  **Example**: Count the airports grouped by `InCity->City->InCountry->Country`
  **Query**: 
```groovy
g.V().has("kind", "thing").has("classId", "class_6").group().by(
  out("prop_21").has("classId", "class_3").out("prop_17").has("classId", "class_5").values("prop_1e")
).by(
  fold()
    .match(
      __.as("a").count(local).as("count"),
    )
      .select("count")
  )
```
**returns:**
```json
{
   "data": [
     {
       "Germany": 2,
       "Netherlands": 2
     }
   ],
   "meta": {}
 }
```
* [x] Gremlin query to get `mode`, `median`, etc.
  * [x] mode
    * ~~can be done with `<removed>`~~
    * ~~requires post-processing~~
    * without post processing: `      __.as("a").unfold().values("prop_18").groupcount()
          .order(local).by(values, decr).select(keys).limit(local, 1).as("prop_19__mode")`
* [x] select multiple properties in single query and group by property:
  **Query**
```grovy
g.V().has("kind", "thing").has("classId", "class_3").group().by(out("prop_17").values("prop_1e")).by(
  fold()
    .match(
      __.as("a").unfold().values("prop_18").count().as("prop_18__count"),
      __.as("a").unfold().values("prop_18").max().as("prop_18__max"),
      __.as("a").unfold().values("prop_18").mean().as("prop_18__mean"),
      __.as("a").unfold().values("prop_19").count().as("prop_19__count"),
    )
        .select("prop_18__count", "prop_18__max", "prop_18__mean").as("population")
        .select("prop_19__count").by(project("prop_19__count")).as("otherprop")
        .select("population", "otherprop")
    )
```
**results in:**
```json
{
  "data": [
    {
      "Germany": {
        "otherprop": {
          "prop_19__count": 2
        },
        "population": {
          "prop_18__count": 2,
          "prop_18__max": 3470000,
          "prop_18__mean": 2035000
        }
      },
      "Netherlands": {
        "otherprop": {
          "prop_19__count": 2
        },
        "population": {
          "prop_18__count": 2,
          "prop_18__max": 1800000,
          "prop_18__mean": 1800000
        }
      }
    }
  ],
  "meta": {}
}

```

**Comment by etiennedi** [comment]
@laura-ham 

I have a few questions on `Local { Aggregate {} }`:

Using this example 
``` graphql
{
  Local {
    Aggregate {
      Things {
        City(groupBy: ["InCountry", "Country", "name"]) {
          maximum {
            population
          }
          groupedBy {
            path
            value
          }
        }
      }
    }
  }
}
```

1. What would a sample response look like, the prototype didn't return anything for this query unfortunately? I could imagine the following response, would this be correct? 

```json
{
  "City": [
    {
      "maximum":{"population": 3000000},
      "groupedBy": {"path":["InCountry", "Country", "name"], "value": "Germany" }
    },
    {
      "maximum":{"population": 5000000},
      "groupedBy": {"path":["InCountry", "Country", "name"], "value": "UK" }
    },
  ]
}
```

2. What's the motivation (this could be explained by answering question 1 as well) behind having the tree structure like `Class -> AggregatorFn -> PropertyName`. These kinds of queries are somewhat similar to `GetMeta`, however there we have the order the other way round: `Class -> PropertyName -> MetaFn`. Is there a reason to do it differently here? If not, is there a possibility we could switch it around so that both APIS would me more consistent?

**Comment by laura-ham** [comment]
1. It is correct that the prototype doesn't return anything on `Aggregate{}` queries. I made the query design, but not the implementation with data. Sorry that I haven't been clear in the docs, in stating what the result would be.. Your guess is right thought ;)
2. Fair point. It was designed like this to stay closest to some Grouping/Aggregation functions I got inspired by when designing this function for our graphql implementation. But I actually agree that flipping the function and property around makes more sense.. @JeroenStravers1 @jeroenstraverskpn what do you think, do buI forget something why we chose to design it this way?

**Comment by etiennedi** [comment]
Thanks!

1. No worries, happy that I figured it out correctly.
2. From my initial research on how do to this with janus/gremlin, we'd get a flat list from janus graph back anyway (something like `population__max`, `population__min`, `area__max`, `area__min`) so the "unflattening" would happen in our code anyway. The upside of that is we'll be quite flexible in how we want to group it for the GraphQL API. Long story short: I don't mind going one way and assuming it'll change soon. ;)

**Comment by jeroenstraverskpn** [comment]
It should be fine to switch them imo. I reread our Slack history to be sure but couldn't find anything regarding the order of these elements

**Comment by laura-ham** [comment]
Okay thanks both. To keep consistency between GetMeta and Aggregation, I will change the design of Aggregate accordingly.

**Comment by etiennedi** [comment]
@laura-ham while we are now much closer to `GetMeta` in structure we still have two names for the same kind of meta/aggregator function, such as

* `maximum` vs `highest`
* `minimum` vs `lowest`
* `average` vs `mean`

Should we also adjust those to each other? If so, I think I'd prefer keeping the names we have in aggreagate (`maximum`, `minimum`, `mean`) etc, they sound "more professional" to me.
