### ISSUE TITLE
Resolve Network Fetch.{Things,Actions}

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#709]
This was originally the scope for #645, however, we then decided to build a local fetch first. In turn we have outscoped everything related to network queries to this issue.

## Todos
* [x] build graphql layer
* [x] extract common filters (local,network) into independent package
* [x] build network layer (aggregate from all peers)
* [x] verify end-to-end
