### ISSUE TITLE
Validate scaling capabilities

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#713]
This is to track all changes around the scaling validation task. We want to find out if each component scales as well as we assumed.

## Todos
* Improve Importing speed to a more reasonable amount
  * [x] POC different batch importing strategy
  * [x] turn POC code into production quality
  * [x] gather further best practices around batch importing (external help)
    * batching `g.AddV()` together does improve performance ([Source](https://www.experoinc.com/post/janusgraph-nuts-and-bolts-part-1-write-performance))
    * too long batches lead to `StackOverflowErrors` ([Source](http://tinkerpop.apache.org/docs/current/recipes/#long-traversals))
* [ ] update helm chart
* [ ] add lock-less operation mode for importing only
* ~~fix ineffecient querying in `Local Get`, see #612~~
  * scoping out because it is a bit bigger than initially assumed, there's not just N+1 queries for multiple classes, but each outgoing edge (cross-ref) is yet another query. It already works for queries without cross-refs. But is currently on a branch that only becomes mergeable when we rewrite how cross-refs are built as well. Unfortunately that's a bit to big to fit into this wrap up task here.
* Make sure all required queries work at all levels
  * [ ] Introduce Spark

**Comment by etiennedi** [comment]
Closing as we have proven that the system can be scaled and have gained new learnings on how to improve the API design and UX topics.
