### ISSUE TITLE
Introduce Spark for OLAP with Janusgraph/C*/ES setup

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#719]
In #713 we have shown that around the 10k vertices mark, analytical queries without an external bigdata tool already start failing.

With Spark we hope to raise that limit by several orders of magnitude

## Todos
* [x] Spike out Spark setup with `docker-compose` and gather learnings
  * exact version matching is very important
    * we cannot use janusgraph 0.2.0 with the jars copied from 0.2.2 for example
    * spark 1.6.2 worked fine with Janusgraph 0.2.2, whereas 1.5.0 failed with cryptic errors
    * there is an operator, but only supports spark 2.x
    * there is an official image that only provides 1.5.1
    * there are some base images provided by Big Data Europe
      * [Spark Master (Dockerhub)](https://hub.docker.com/r/bde2020/spark-master/tags)
      * [Spark Worker (Dockerhub)](https://hub.docker.com/r/bde2020/spark-worker/tags)
      * we need to build custom images because we also need to include the janusgraph jars, but we can either base them on the bde images or at least build images inspired by them
* [x] build required images
* ~~ introduce into helm chart~~ outscoped to infra repo (non-public)
* [x] inform about best ways to integrate with weaviate (with external help)
  * e.g. how do we deal with the sync/blocking nature of what should be a job running in the background

**Comment by etiennedi** [comment]
Depends on #744

**Comment by etiennedi** [comment]
Closing, as this was mostly evaluation and the production implementation is coming with #720.
