### ISSUE TITLE
Remove pagination from Local/Network { Get }

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#745]
## Why?
- Pagination in Janusgraph is not something we'd get for free for large data sets
- So far we just assumed paging through large datasets is something we could easily do, but haven't tied this to a specific use-case
- Upon further investigation we have realized we don't see any use cases

## Todos
* [x] Replace pagination (`first`, `after`) with simple `limit`
  * @laura-ham ham, do we also want to call it `limit` or keep the word `first`. I think I'm in favor of `limit`, because `first` reminds me too much of pagination features. Opinions?
  * [x] in GQL `Local { Get }`
  * [x] in GQL `Network { Get }`
  * [x] in all `GET /{things,actions}/`
* [x] is pagination currently mentioned anywhere in the docs? If so, it has to be adapted.

**Comment by etiennedi** [comment]
Added the `Bad UX` label because in the current state, the feature is present, but doesn't really work.

**Comment by laura-ham** [comment]
> do we also want to call it `limit` or keep the word `first`. I think I'm in favor of `limit`, because `first` reminds me too much of pagination features. Opinions?

Yes, I vote for replacing it by `limit` as well.

**Comment by etiennedi** [comment]
Closing, changes will be merged with #826
