### ISSUE TITLE
Add Batch Cross-ref importer

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#788]
The Proposal was discussed in #781. Creating a new issue to track the implementation.

## Todos

* [x] rename `/<kinds>/<uuid>/properties/<propName>` to `/<kinds>/<uuid>/references/<propName>`
* [x] add new structure for batch importing cross-refs
* [x] build handler (ignore validation)
* [x] add validation
  * keep in mind that batch importing is a less-restrictive mode than regular operation. So we only need minimal validation
* [x] add db connector method (in janusgraph)
* [ ] document what makes the Batch Import special (and potentially dangerous)
* [ ] remove `async` option from all batch import endoints

**Comment by etiennedi** [comment]
FYI @bobvanluijt @laura-ham - something I only realized now:

Since the Batch importer's goal is speed, it must avoid all slow patterns (similar to the other batch importers). This also means the validation will be minimal. This in turn means that this importer is somewhat dangerous because you can actually import stuff that doesn't make sense if you're not 100% sure what you're doing. As a result I'll add a warning to the docs.

Here's what we can validate and cannot validate:

* ✅ Are the `from` and `to` strings in the correct format, i.e. do we have a peer name, a valid kind, a uuid (and in the case of the source, is the prop set) -> we can easily validate this
* ⚠️ Does the specified uuid (both source and target actually exist)? We cannot validate this prior to sending the request off to the db, however, it will at least fail in the DB if either doesn't exist
* ❌ Does the source class actually have the property that the user specified? We cannot validate this at all. In order to validate this, we'd need to do a "read before write" which would defeat the whole point of batch importing. We can validate whether this property exists at all (because we have a mapping of all properties), but we cannot check if it's part of this particular source class. Because we don't know the source class at all. If we wanted to find out, we'd first need to do a "get thing/action by uuid" from the db for each result, and then we wouldn't be any faster then just adding one ref at a time.

Having said that, while this is quite dangerous, I think this is a trade-off that's ok for the batch import. Otherwise we simply don't have a way of importing large datasets. But we need to make very sure that the user understands what they're doing.

My suggestion would be to add this to the docs and also add a link to this section in the docs to the swagger description fields. Do you think that's enough?

**Comment by bobvanluijt** [comment]
> My suggestion would be to add this to the docs and also add a link to this section in the docs to the swagger description fields. Do you think that's enough?

@etiennedi, I think that the pragmatism in this approach is best. Can you please create an issue for me when it is ready so that I know _what_ to add?
