### ISSUE TITLE
Telemetry: create acceptance test

### ISSUE THREAD

**Issue by JeroenStravers1** [creativesoftwarefdn/weaviate#803]
## Reason
I want to make sure logging of requests is handled correctly, unit tests only go so far.

## Tasks
- [x] SETUP a mock endpoint 
  - [x] setup basic endpoint in test env
  - [x] determine required functions
  - [x] determine how to succesfully run `go build && ./<filename>` from another folder than `main`
  - [x] implement in the acceptance test
    - [x] setup to use cbor posts
    - [x] determine which port to use
- [x] CREATE a single acceptance test
  - [x] determine which specific endpoint to test
  - [x] create a single weaviate endpoint request
  - [x] create mock endpoint request
  - [x] compare results
  - [x] pass test
- [x] MOVE feature flag, interval and url settings to config
  - [x] read conf into requestsLog from configure server
    - [x] handle any errors here
  - [x] add different `url` and `interval` for `debug` conf 
- [x] INTEGRATE acceptance test in Travis
- [ ] ~~ADD more acceptance tests~~ I imagined making an acceptance test for each endpoint, but the test architecture invalidates that approach
related: #699

**Comment by etiennedi** [comment]
@JeroenStravers1 can this be closed?

**Comment by JeroenStravers1** [comment]
Closing gh-803 as the acceptance test is fully functioning
