### ISSUE TITLE
Resolve Network Aggregate (by proxying to remote peer)

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#812]
## Todos
* [x] add resolver in graphql package
* [x] add proxy method in network package
* [ ] verify end to end
