### ISSUE TITLE
Make REST api more RESTful / Remove unexpected behavior

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#826]
## Background
Over the last couple of weeks we have identified a few places in the API that cannot be considered intuitive, as they sometimes behave differently. This includes endpoints that don't describe resources, describe different resources for the same path depending on the verb used, etc.

These were mostly discovered when using the APIs through UI clients by @dljcollete, when writing Getting Started Guides and Docs by @bobvanluijt or when looking at Bugs and Implementation tasks by @etiennedi.

## Scope In

This issues should cover all API level breaking changes and mark the final breaking changes before making our first tagged release

## Scope Out

Anything that's non breaking (Tech Debt Clenaup) etc is not included here, as this will follow AFTER the MVP release, but we need to group the breaking changes before the release.

## Todos

* [x] Remove `async` option from all endpoints
* [x] Check for scenarios where different HTTP VERBS lead to different bodies and fix them
  * [x] https://github.com/creativesoftwarefdn/weaviate/issues/823
  * [x] `/things/`
  * [x] `/actions/`
  * [x] `/schema/things`
  * [x] `/schema/actions`
  * [x] update docs
* [x] clean up config: https://github.com/creativesoftwarefdn/weaviate/issues/800
  * [x] remove multiple enviroments per file
  * [x] remove deprecated fields, also see 
https://github.com/creativesoftwarefdn/weaviate/issues/576 and https://github.com/creativesoftwarefdn/weaviate/issues/499
* [x] clean up debugging leftovers: https://github.com/creativesoftwarefdn/weaviate/issues/774
* [x] replace pagination with limit in GQL: https://github.com/creativesoftwarefdn/weaviate/issues/745
* [x] replace panics with proper error handling: https://github.com/creativesoftwarefdn/weaviate/issues/654, also see https://github.com/creativesoftwarefdn/weaviate/issues/617
* [x] remove history endpoints
* [x] remove broker related stuff
* [x] change `@class` to `class`, `@dataType` to `dataType`
* [x] remove `@context`
* [x] remove keys from payloads

## BREAKING CHANGES ADDED:
* `POST /things` no longer returns `202 or 200`, only returns `200` now
* `POST /actions` no longer returns `202 or 200`, only returns `200` now
* `PUT /things/<id>` no longer returns `202`, but `200`
* `PUT /actions/<id>`  no longer returns `202`, but `200`
* Method signatures for auto-generated Go client for `ThingsUpdate`, `ActionsUpdate`, `ThingsCreate`, `ActionsCreate` changes from three to two arguments as there is only one success option, no longer two
* Payloads for all VERBs for `/things` are now the same, please see `swagger.json`
* Payloads for all VERBs for `/actions` are now the same, please see `swagger.json`
* IDs are now simply called `id` on their respective resource, i.e. we would now have an `action.id` rather than `action.actionId`, same is true for `thing.id`.
* structure of `config.yaml` or `config.json` was changed, it no longer contains multiple "environments", but one set of configuration parameters
* flag `--config` is no longer supported, because there is no more option to include multiple environments in a config file
* Pagination replaced by Limit: In REST API query params `first`, `after` removed, `limit` added. Same for GQL API in `Local { Get }` and `Network { Get }`
* removed `@context` field alltogether
* renamed `@class` to `class` and `@dataType` to `dataType` field in schema, thing and action bodies
