### ISSUE TITLE
Startup issues with docker-compose stack on smaller machines

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#850]
We have received unspecific feedback that starting our entire stack on docker-compose as outlined in the "Getting Started" docs isn't always successful.

While development machines (macOS) tend to be fine, I was able to reproduce some issues with smaller Debian based VMs on GCE

## Example Cases

1. `n1-standard-1` (1 cpu, 3.75GB mem) with Debian: Fails allocating memory for scylla/cassandra, because elasticsearch eats up all the available memory

## Todos

* [x] try to control memory usage of elasticsearch
  * [x] experiment what a good minimal es heap config is: 300mb turned out absolutely fine for testing purposes
* [x] update docker-compose.yml
* [x] update docs
