### ISSUE TITLE
Improved behaviour when adding to the ontology-schema

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#856]
Because the next step in Weaviate will be increasing the role of the c11y, Weaviate should become more strict about the use of words in;
- class names (for all concepts)
- property names
- keywords

# Todo

All the above should be validated accordingly to;
1. The individual words should be in the c11y.
2. [CamelCase](https://github.com/creativesoftwarefdn/weaviate/blob/master/docs/en/use/ontology-schema.md#defining-classes) format.
3. The individual words should compile for the regex: `^[A-Za-z][\A-Za-z]*$` (i.e.; `regexp.MustCompile('^[A-Za-z][\A-Za-z]*$')`

### Additional

1. The behavior of creating classes and properties should be agnostic of the casing. For example, adding the class name: `zoo` should be valid (if in the c11y) and automatically translate to: `Zoo`. Visa Versa for keywords. the keyword: `Name` should be valid (if in the c11y) and stored as `name`. This _only_ goes for the first character.
2. Please reflect in the docs.

**Comment by bobvanluijt** [comment]
cc: @laura-ham

**Comment by etiennedi** [comment]
@bobvanluijt Regarding your "Additional" Bullet 1: Does this only apply during creation time or should this also apply when referencing a class? I.e. when creating a Thing, should the user be able to specify `{ "class": "zoo" }` or should they have to specify `{"class": "Zoo"}`?

**Comment by etiennedi** [comment]
@bobvanluijt The regex you specified in Todo 3 also allow for spaces. Currently we don't allow spaces and force the user to use the CamelCase format. Are you sure spaces should be valid?

**Comment by etiennedi** [comment]
@bobvanluijt The docs about `CamelCase` you linked, talk about `CamelCase` (i.e. capital C in the beginning), but then provide examples for `camelCase` (i.e. lowercase c in the beginning): https://github.com/creativesoftwarefdn/weaviate/blob/master/docs/en/use/ontology-schema.md#camelcase

To be consistent with what you wrote above the rules should in my opinion be:
1. class name: `CamelCase`
2. property name: `camelCase`.

Then there is another question around keywords: We can already set multiple ones and even provide weights. Should it still be possible to use `camelCase` for a single keyword? If so that also implies logic changes, because then we also have to build the centroid for each keyword on its own, then build another centroid from class name and the keyword centroids.

**Comment by bobvanluijt** [comment]
Hi @etiennedi, 

Answers per questions;

1. On creation is enough. We want to store them correctly. Maybe -for UX purposes- we might add this later as well.
2. Yeah, that is a good point. I've updated the question. (I understand the confusion. The reasoning was that this is the regex _after_.) So as it is updated, this should compile.
3. Sharply seen. You observation is exactly correct (maybe also add this to the docs). A Class = UpperCamel and a property is lowerCamel.
4. Ahh, again a good one! No, I would argue for MVP state _only lowercase_ for keywords, no camelCassing. You can't concatenate words in keywords.

**Comment by etiennedi** [comment]
## Todos

* [ ] class names
  * [ ] allow lower-case name, but convert to upper-case before storing
  * [ ] validate each CamelCased word matches regex
  * [ ] validate each CamelCased word present in c11y
* [ ] propertyNames
  * [ ] allow  upper-case name, but convert to lower-case before storing
  * [ ] validate each camelCased word matches regex
  * [ ] validate each CamelCased word present in c11y
* [ ] keywords
  * [ ] only allow all lowercase letters
  * [ ] validate entire keyword string is present in the c11y
